version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: svc-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: svc-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: >
      npm run dev

